chapter_79
velicham-onlive/velicham-onlive.github.io pull request #87
Opened 2020-06-14 13:17 UTC by febincp6

2020-06-16 12:03 UTC, faisalmohd83 requested changes
@febincp6 found the CDATA is missing one square bracket in the end `</p>]]>`. Please refer to previous chapters.

2020-06-16 12:06 UTC, faisalmohd83 commented
@hafizkvpg @sajadhaja Can we add GitHub actions to check the HTML/XML lint?

2020-06-16 18:18 UTC, sajadhaja commented
Lint issues can be check using ES Lint plugin which is very popular.We can configure eslint rules and using npm manager we can execute the lint command to verify those configured rules.
Reference:-
ES Lint plugin: https://www.npmjs.com/package/eslint-plugin-html

Answer to your question, I seen some plugin available in github market place to run such ESLint check. Finally those rules should be configured in our code base and using npm command they are executing those rules.
Reference for Github ES Lint Check:-
- https://github.com/marketplace/actions/eslint-checker
- https://github.com/ninosaurus/eslint-check

2020-06-21 18:35 UTC, faisalmohd83 commented on podcast.rss
>        <title>592  സൂറഃ നാസിയാത്ത് ആമുഖം_a</title>
Can we follow the same format in item title as we did for previous chapters?

` <title>590.സൂറഃ നാസിയാത്ത് പാരായണം Part 1</title>`
` <title>592  സൂറഃ നാസിയാത്ത് ആമുഖം_a</title>`

2020-06-21 18:38 UTC, faisalmohd83 commented on podcast.rss
>        <title>596  സൂറഃ നാസിയാത്ത്  ആയത്ത്  6-9 part 1_a</title>
Let's maintain consistency between words. For e.g., below title had more than single space between words.

`<title>597   സൂറഃ നാസിയാത്ത്   ആയത്ത് 5-9 Part 2_a</title>`

2020-06-21 18:50 UTC, faisalmohd83 commented on podcast.rss
>        <title>608  സൂറഃ നാസിയാത്ത്  ആയത്ത് 20.21&22 Part 1_a</title>
The `&` sign to be replaced with `&amp;` in titles, please check other occurrences too.

2020-06-21 19:08 UTC, faisalmohd83 commented on podcast.rss
>        <title>617  സൂറഃ നാസിയാത്ത്  ആയത്ത് 30&31_a</title>
Please remove *_a*

2020-06-21 19:09 UTC, faisalmohd83 commented on podcast.rss
>        <title>613  സൂറഃ നാസിയാത്ത്  ആയത്ത് 25&26 Part 1_a</title>
Please remove **_a**, found in many other titles too

2020-06-21 19:23 UTC, faisalmohd83 commented on podcast.rss
> +        <![CDATA[<p>Velicham Quran Dars series</p><p>Qur'an class #624💠Surah An-Naziat 💠</p><p>*ആയത്ത്&zwnj; - 45* إِنَّمَآ أَنتَ مُنذِرُ مَن يَخْشَىٰهَا നിശ്ചയം നീ അതിനെ ഭയപ്പെടുന്നവർക്ക്&zwnj; താക
An issue in the text to HTML conversion. Let's use https://wordhtml.com/ to convert the texts to Html with compress option. The compress option is avail in the second tab(HTML) of the https://wordhtml.com/ site.

The text pushed:
`<![CDATA[<p>Velicham Quran Dars series</p><p>Qur'an class #624💠Surah An-Naziat 💠</p><p>*ആയത്ത്&zwnj; - 45* إِنَّمَآ أَنتَ مُنذِرُ مَن يَخْشَىٰهَا നിശ്ചയം നീ അതിനെ ഭയപ്പെടുന്നവർക്ക്&zwnj; താക്കീതു നൽകുന്നവൻ മാത്രമാണ്. 🔸Admin Team Velicham Onlive🔸</p>]]>`

--
A sample converted for reference with compress option.
`<p>Velicham Qur&rsquo;an Dars series</p><p>Qur'an class #624</p><p>💠Surah An-Naziat 💠<br />ആയത്ത്&zwnj; - 45</p><p>إِنَّمَآ أَنتَ مُنذِرُ مَن يَخْشَىٰهَا <br /> നിശ്ചയം നീ അതിനെ ഭയപ്പെടുന്നവർക്ക്&zwnj; താക്കീതു നൽകുന്നവൻ മാത്രമാണ്.</p><p>🔸Admin Team Velicham Onlive🔸</p>`

2020-06-21 19:24 UTC, faisalmohd83 requested changes
@febincp6 please address the new comments

2020-07-02 09:36 UTC, faisalmohd83 commented on podcast.rss
> +        <![CDATA[<p>Velicham Quran Dars series</p><p>Qur'an class #624💠Surah An-Naziat 💠</p><p>*ആയത്ത്&zwnj; - 45* إِنَّمَآ أَنتَ مُنذِرُ مَن يَخْشَىٰهَا നിശ്ചയം നീ അതിനെ ഭയപ്പെടുന്നവർക്ക്&zwnj; താക
@febincp6 Can you look at this comment? It might be worth looking at each verse for the same issue.

2020-10-11 23:25 UTC, faisalmohd83 approved these changes

2020-10-11 23:26 UTC, merged

2020-10-11 23:26 UTC, faisalmohd83 commented
Closes #87